# Use root/example as user/password credentials
version: "3.9"

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password # pragma: allowlist secret
      MYSQL_DATABASE: baseball

    # mounting baseball.sql and finalsql.sql in docker-entrypoint-initdb.d folder, because container
    # will automatically run sql files in this folder. I renamed finalsql.sql to cassignment5sql.sql in container
    # because files are run in alphabetical order in this folder, so I need the "baseball.sql" file to run first in order
    # to initialize the baseball database first, then extract features from finalsql.sql
    # https://serverfault:com/questions/796762/creating-a-docker-mysql-container-with-a-prepared-database-scheme
    volumes:
      - "./baseball.sql:/docker-entrypoint-initdb.d/baseball.sql"
      - "./Assignments/finalsql.sql:/docker-entrypoint-initdb.d/cfinalsql.sql"

  pyscript:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    # this will mount the results from the script from the container back to the host machine in finalResults directory
    volumes:
      - "./finalResults:/finalTables"
